services:
  shortener-app:
    container_name: shortener
    networks:
      - shortener
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment: 
        - DB_DRIVER=${DB_DRIVER:-postgres}
        - DB_USER=${DB_USER:-postgres}
        - DB_PASSWORD=${DB_PASSWORD:-postgres}
        - DB_PORT=${DB_PORT:-5432}
        - DB_HOST=${DB_HOST:-postgres-shortener}
        - DB_NAME=${DB_NAME:-shortener_db}
        - REDIS_ADDR=${REDIS_ADDR:-redis-shortener:6379}
    restart: unless-stopped
    depends_on:
      - postgres-shortener
      - redis-shortener

  postgres-shortener:
    image: postgres:15
    container_name: postgres-shortener
    networks:
      - shortener
    environment:
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
      - POSTGRES_DB=${DB_NAME:-shortener_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-postgres}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

  redis-shortener:
    image: redis:7
    container_name: redis-shortener
    networks:
      - shortener
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 15s

networks:
  shortener:

volumes:
  postgres-data:
  redis-data: